### ISSUE TITLE
CUDA 8 compatibility

### ISSUE THREAD

**Issue by acharara** [ecrc/kblas-gpu#1]
Compilation errors with CUDA 8, naming conflicts with new functions introduced in cuda 8. To be resloved.

**Comment by ltaiefhatem** [comment]
Our functions are prefixed with kblas. Which functions triggered these conflicts?

**Comment by acharara** [comment]
Its an operator function newly introduced in CUDA 8, that was already defined in KBLAS.
Issue resolved with pull request #3

**Comment by acharara** [comment]
@egonzalf please notify us -when thourough testing is conducted- on whether we can close this issue.
Thanks

**Comment by acharara** [comment]
The error when compiling with CUDA 8.0 is resolved with pull request #3.
Closing.
